#!/bin/bash

### BEGIN INIT INFO
# Provides:          nginx
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Lightweight SOCKS5 proxy tool
# Description:       Start or stop the nginx server
### END INIT INFO

NAME="nginx"
NAME_BIN="nginx"
FOLDER="/home/lhteth/nginx/"
BIN="/home/lhteth/nginx/sbin/nginx"


check_running(){
	PID=`ps -ef |grep -v grep | grep nginx |awk '{print $2}'`
	if [[ ! -z ${PID} ]]; then
		return 0
	else
		return 1
	fi
}
do_start(){
	check_running
	if [[ $? -eq 0 ]]; then
	echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME (PID ${PID}) 正在运行..." && exit 0
	else
		cd ${FOLDER}
		#python_ver=$(ls /usr/bin|grep -e "^python[23]\.[1-9]\+$"|tail -1)

		nohup  "$BIN" &
		sleep 2s
		check_running
		if [[ $? -eq 0 ]]; then
			echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME 启动成功 !"
		else
			echo -e "${Error_font_prefix}[错误]${Font_suffix} $NAME 启动失败 !"
		fi
	fi
}
do_stop(){
	check_running
	if [[ $? -eq 0 ]]; then
		kill -9 ${PID}
		RETVAL=$?
		if [[ $RETVAL -eq 0 ]]; then
			echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME 停止成功 !"
		else
			echo -e "${Error_font_prefix}[错误]${Font_suffix}$NAME 停止失败 !"
            killall nginx
			echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME 强行停止 !"
		fi
	else
		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME 未运行 !"
		RETVAL=1
	fi
}
do_status(){
	check_running
	if [[ $? -eq 0 ]]; then
		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME (PID ${PID}) 正在运行..."
	else
		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME 未运行 !"
		RETVAL=1
	fi
}

do_reload() {
    /home/lhteth/nginx/sbin/nginx -s reload
}

do_restart(){
	do_stop
	do_start
}
case "$1" in
	start|stop|restart|status|reload)
	do_$1
	;;
	*)
	echo "使用方法: $0 { start | stop | restart | status | reload }"
	RETVAL=1
	;;
esac
exit $RETVAL