#!/bin/bash

### BEGIN INIT INFO
# Provides:          nginx
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Lightweight reverse proxy tool
# Description:       Start or stop the nginx server
### END INIT INFO

#!/bin/sh
#
#chkconfig: 2345 80 90
#description: nginx
start() {
    /home/lhteth/nginx/sbin/nginx
}
reload() {
    /home/lhteth/nginx/sbin/nginx -s reload
}
stop() {
    /home/lhteth/nginx/sbin/nginx -s quit
}
case "\$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  reload)
    reload
    ;;
  *)
echo $"Usage: $0 {start|stop|restart|reload}"
exit 1
esac
exit $RETVAL
